version: '3.3'
volumes:
  static: {}

services:
  db:
    platform: linux/x86_64
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

  vpn_service:
    platform: linux/x86_64
    build: .
    expose:
      - "8000"
    command:
      sh -c "./migrate.sh && ./start.sh"
    depends_on:
      - db
    restart: always

  nginx:
    build: ./nginx_conf
    ports:
      - "8080:80"
    volumes:
      - static:/usr/src/static
    restart: always
    depends_on:
      - vpn_service
