version: '3'

services:
  db:
    platform: linux/x86_64
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

  vpn_service:
    platform: linux/x86_64
    build: .
    ports:
      - "8000:5000"
    command:
      sh -c "./migrate.sh && ./start.sh"
    depends_on:
      - db
    restart: always

  nginx:
    platform: linux/x86_64
    build: ./nginx
    ports:
      - "8000:5000"
    depends_on:
      - vpn_service
    restart: always
