version: '3.3'
volumes:
  static: {}
  database-data:

networks:
  backnet:
  frontnet:

services:
  db:
    container_name: 'PostgresSQL'
    platform: linux/x86_64
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backnet
    volumes:
      - database-data:/var/lib/postgresql/data/

  back_api_admin:
    container_name: 'BackApiAdmin'
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Docker/back-api-admin/Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command:
      sh -c -m "./sh_scripts/migrate.sh && ./sh_scripts/start_gunicorn.sh"
#      sh -c -m "./sh_scripts/makemigrations.sh && ./sh_scripts/migrate.sh && ./sh_scripts/start_gunicorn.sh"
    volumes:
      - static:/usr/src/static
    depends_on:
      - db
    restart: always
    networks:
      - backnet
      - frontnet

  background_tasks:
    container_name: 'BackgroundTasks'
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Docker/background-tasks/Dockerfile
    command: sh -c -m "./sh_scripts/start_scheduler.sh"
    depends_on:
      - db
    restart: always
    networks:
      - backnet

  proxy:
    container_name: 'Nginx'
    build: ./Docker/nginx_conf
    ports:
      - "8080:80"
    volumes:
      - static:/usr/src/static
    restart: always
    depends_on:
      - back_api_admin
    networks:
      - frontnet
      - backnet

  bot_tg_client:
    container_name: 'TelegramClientBot'
    build: ./bots/telegram_client_bot
    restart: always
    env_file: .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN_CLIENT}
      - USERNAME=${USERNAME_CLIENT}
      - PASSWORD=${PASSWORD_CLIENT}
    command:
      sh -c -m "./start_bot.sh"
    depends_on:
      - proxy
    networks:
      - frontnet
      - backnet

  bot_tg_admin:
    container_name: 'TelegramAdminBot'
    build: ./bots/telegram_admin_bot
    restart: always
    env_file: .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN_ADMIN}
      - USERNAME=${USERNAME_ADMIN}
      - PASSWORD=${PASSWORD_ADMIN}
    command:
      sh -c -m "./start_bot.sh"
    depends_on:
      - proxy
    networks:
      - frontnet
      - backnet