bot:
  name: "test_admin_telegram_bot"
  admin_tech: [480629416, 1416920102]
  api:
    url: "proxy:8080/"
    uris: {
      "health": "health/check/",
      "get_auth_token": "api/api-token-auth/",

      "get_tariffs": "api/tariff/",
      "get_vpn_servers": "api/vpn-servers/",
      "get_transports": "api/transports/",

      "get_client_tokens": "api/token/{transport_name}/{messenger_id}",
      "get_token_info": "api/token/{token_id}",
      "get_contact": "api/contact/{transport_name}/{messenger_id}",

      "creat_or_update_contact": "api/contact/",
      "renew_exist_token": "api/token/renew/",
      "create_new_token": "api/token/new/",
      "update_token": "api/token/",
      "delete_token": "api/token/delete/",
      "telegram_message_send": "api/message/telegram/send/",
      }