# Generated by Django 4.1.4 on 2022-12-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline_vpn_admin', 'fill_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок активности тарифа'),
        ),
        migrations.AlterField(
            model_name='tokenprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='tokenprocess',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='vpnserver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='vpnserver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='vpntoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='vpntoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='vpntoken',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
    ]
