# Generated by Django 4.1.3 on 2022-11-03 19:06

import apps.outline_vpn_admin.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='ФИО')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'Client',
            },
            bases=(models.Model, apps.outline_vpn_admin.models.DictRepresentationMixin),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='Буквенный код валюты по ISO 4217')),
                ('name_iso', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Цифровой код валюты по ISO 4217')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная валюта')),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Курс к основной валюте')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность валюты')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'Currency',
            },
            bases=(models.Model, apps.outline_vpn_admin.models.DictRepresentationMixin),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Имя тарифа')),
                ('prolong_period', models.IntegerField(verbose_name='Срок продления в днях')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('traffic_limit', models.IntegerField(verbose_name='Ограничение трафика в байтах')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Срок активности тарифа')),
                ('is_demo', models.BooleanField(default=False, verbose_name='Демо тариф')),
                ('is_tech', models.BooleanField(default=False, verbose_name='Технический тариф')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность тарифа')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления записи')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outline_vpn_admin.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
                'db_table': 'Tariff',
            },
            bases=(models.Model, apps.outline_vpn_admin.models.DictRepresentationMixin),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название бота')),
                ('uid_format', models.CharField(help_text='Наименование уникального идентификатора в credentials. {поле_уникального_идентификатора}', max_length=254, verbose_name='Формат уникального идентификатора бота')),
                ('full_name_format', models.CharField(default='', help_text='Наименование полей в credentials для формирования имени клиента. {Поле_1} {Поле_2} и т.д.', max_length=254, verbose_name='Формат имени клиента')),
                ('credentials', models.JSONField(verbose_name='Реквизиты бота')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'db_table': 'Transport',
            },
            bases=(models.Model, apps.outline_vpn_admin.models.DictRepresentationMixin),
        ),
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Внутреннее имя VPN сервера')),
                ('external_name', models.CharField(max_length=254, verbose_name='Внешнее имя VPN сервера')),
                ('uri', models.CharField(max_length=254, verbose_name='URI для создания ключей OutLine')),
                ('is_default', models.BooleanField(default=False, verbose_name='Сервер по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'VPNServer',
                'verbose_name_plural': 'VPNServers',
                'db_table': 'VPNServer',
            },
            bases=(models.Model, apps.outline_vpn_admin.models.DictRepresentationMixin),
        ),
        migrations.CreateModel(
            name='VPNToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_id', models.BigIntegerField(blank=True, null=True, verbose_name='VPN Token ID on VPN Server')),
                ('previous_vpn_token_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID предыдущего VPN ключа')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Имя VPN ключа')),
                ('vpn_key', models.TextField(blank=True, null=True, verbose_name='VPN ключ')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность VPN ключа')),
                ('is_demo', models.BooleanField(default=False, verbose_name='Демо')),
                ('traffic_limit', models.BigIntegerField(blank=True, null=True, verbose_name='Лимит трафика')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline_vpn_admin.client', verbose_name='Владелец ключа')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outline_vpn_admin.vpnserver', verbose_name='VPN сервер')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outline_vpn_admin.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'VPNToken',
                'verbose_name_plural': 'VPNTokens',
                'db_table': 'VPNToken',
            },
            bases=(models.Model, apps.outline_vpn_admin.models.DictRepresentationMixin),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='<Transport.name>@<Transport.uid_format>', max_length=254, verbose_name='Идентификатор контакта')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Название контакта')),
                ('credentials', models.JSONField(blank=True, null=True, verbose_name='Реквизиты пользователя')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline_vpn_admin.client', verbose_name='Владелец ключа')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outline_vpn_admin.transport', verbose_name='Канал связи')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'Contact',
            },
            bases=(models.Model, apps.outline_vpn_admin.models.DictRepresentationMixin),
        ),
    ]
