# Generated by Django 4.1.4 on 2022-12-12 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline_vpn_admin', '0001_alter_client_created_at_alter_client_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline_vpn_admin.client', verbose_name='Клиент'),
        ),
    ]
