# Generated by Django 4.1.4 on 2022-12-12 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline_vpn_admin', '0003_alter_transport_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='is_admin_transport',
            field=models.BooleanField(verbose_name='Для администраторов', default=False)
        ),
    ]
