# Generated by Django 4.1 on 2022-08-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPNServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(null=True, verbose_name='ID телеграм')),
                ('telegram_login', models.CharField(blank=True, max_length=254, null=True, verbose_name='Логин телеграм')),
                ('telegram_first_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Имя телеграм')),
                ('telegram_last_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Фамилия телеграм')),
                ('outline_key_id', models.IntegerField(blank=True, null=True, verbose_name='ID OutLine VPN Key')),
                ('record_created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('outline_key_valid_until', models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('outline_key_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активность VPN ключа')),
            ],
            options={
                'db_table': 'VPNServiceRecord',
                'verbose_name': 'Telegram User VPN Key',
                'verbose_name_plural': 'Telegram User VPN Keys',
            },
        ),
    ]
