bot:
  name: "test_client_telegram_bot"
  tech_admin: [480629416]
  managers: [480629416, 1416920102]
  api:
    url: "http://api.tematika.org:8080/"
    uris: {
      "health": "health/check/",
      "get_auth_token": "api-token-auth/",
      "get_tariffs": "tariff/",
      "get_contact": "contact/{transport_name}/{messenger_id}",
      "get_client_tokens": "token/{transport_name}/{messenger_id}",
      "creat_or_update_contact": "contact/",
      "renew_exist_token": "token/renew/",
      "create_new_token": "token/new/",
      "get_vpn_servers": "vpn-servers/",
      }