bot:
  name: "test_client_telegram_bot"
  tech_admin: [480629416]
  managers: [480629416, 1416920102]
  api:
    url: "http://proxy:80/"
    uris: {
      "health": "health-check/",
      "get_auth_token": "api/api-token-auth/",
      "get_tariffs": "api/tariff/",
      "get_contact": "api/contact/{transport_name}/{messenger_id}",
      "get_client_tokens": "api/token/{transport_name}/{messenger_id}",
      "creat_or_update_contact": "api/contact/",
      "renew_exist_token": "api/token/renew/",
      "create_new_token": "api/token/new/",
      "get_vpn_servers": "api/vpn-servers/",
      }