django:
#  debug: True
  debug: False
  date_string_format: '%d-%m-%Y'
  allowed_hosts: [
    'api.tematika.org',
    'www.api.tematika.org',
    'http://api.tematika.org',
    'https://api.tematika.org',

    'http://admin.tematika.org',
    'https://admin.tematika.org',
    'www.admin.tematika.org',
    'admin.tematika.org',
  ]
  csrf_trusted_origins: [
    'http://api.tematika.org:8080',
    'https://api.tematika.org:8080',
    'http://api.tematika.org',
    'https://api.tematika.org',
    'http://admin.tematika.org:8080',
    'https://admin.tematika.org:8080',
    'http://admin.tematika.org',
    'https://admin.tematika.org',
  ]

db:
  host: db
  port: 5432
  name: postgres
  user: postgres
  password: postgres
