django:
  debug: True
  secret_key:

logging:
  disable_existing_loggers: true
  formatters:
    default:
      format: '[%(asctime)s] %(levelname)-8s [%(name)s] [line=%(lineno)s] [msg=%(message)s]'
  handlers:
    file:
      backupCount: 30
      class: logging.handlers.TimedRotatingFileHandler
      encoding: utf-8
      filename: logs/vpn.log
      formatter: default
      interval: 1
      level: DEBUG
      when: D
    stdout:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
  root:
    handlers:
      - file
      - stdout
    level: DEBUG
    propagate: true
  version: 1

db:
  host: db
  port: 5432
  name: postgres
  user: postgres
  password: postgres

tg_bot:
  token:
  subscribes: ['1 месяц', '3 месяца', '6 месяцев']

outline_vpn:
  ip: 194.110.55.249
  port: 19600
  server_key: